/**
 * Generates the standalone tracker app in apps/tracker.
 *
 * The tracker deploys as its own Vercel project, which means its source has to
 * live in one self-contained tree. Copying those files by hand would guarantee
 * they drift from the versions the main app actually runs, so they are
 * generated instead: this script is the only thing that writes apps/tracker,
 * and re-running it is how the deployment picks up a change.
 *
 * The standalone app deliberately carries no database code. The tracker reads
 * chain state and nothing else, so dropping Drizzle and Neon also drops the
 * DATABASE_URL and CRON_SECRET the main app's build requires.
 *
 * Run: npm run tracker:build
 */

import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = process.cwd();
const OUT = join(ROOT, "apps/tracker");

function write(rel: string, content: string) {
  const dest = join(OUT, rel);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, content);
}

function copy(rel: string, destRel = rel) {
  const dest = join(OUT, destRel);
  mkdirSync(dirname(dest), { recursive: true });
  cpSync(join(ROOT, rel), dest, { recursive: true });
}

const GENERATED = "/* GENERATED by scripts/build-tracker-app.ts — edit the source, not this copy. */\n";

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

// ---- canonical source, copied verbatim
copy("lib/holders");
copy("features/holders");
copy("features/layout/PageHeader.tsx");
copy("lib/utils.ts");
copy("lib/http.ts");
copy("lib/logger.ts");
copy("lib/brand.ts");
copy("app/api/holders");
copy("docs/whale-tracker.md", "README.md");

// The page moves to the root: this app is only the tracker, so making the
// reader click through to /whales would be pure ceremony.
const page = readFileSync(join(ROOT, "app/whales/page.tsx"), "utf8").replace(
  "export default async function WhalesPage(",
  "export default async function TrackerPage(",
);
write("app/page.tsx", GENERATED + page);

// Only the base layer of the main app's stylesheet: the Tailwind directives,
// the design tokens for both themes, and the element defaults. Everything
// after it is decorative helpers (view transitions, .lift, .link) that the
// tracker's components do not use. Sliced from the source rather than
// rewritten so the tokens cannot drift from the main app's.
const css = readFileSync(join(ROOT, "app/globals.css"), "utf8");
const cutAt = css.indexOf("@view-transition");
write("app/globals.css", cutAt > 0 ? css.slice(0, cutAt).trimEnd() + "\n" : css);

// ---- shell, specific to the standalone app
write(
  "app/layout.tsx",
  GENERATED +
    `import type { Metadata } from "next";
import { Space_Grotesk, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const sans = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
  display: "swap",
});
const mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Whale tracker",
  description:
    "Live holder tracking from chain state: positions ranked as economic actors, with buy/sell behavior and what each stack is worth on exit.",
};

// Match the persisted theme before first paint so the page does not flash.
const noFlash = \`(function(){try{var t=localStorage.getItem('tracker-theme');if(t!=='light'&&t!=='dark'){t=window.matchMedia&&window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';}document.documentElement.setAttribute('data-theme',t);}catch(e){document.documentElement.setAttribute('data-theme','dark');}})();\`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="dark" className={\`\${sans.variable} \${mono.variable}\`}>
      <head>
        <script dangerouslySetInnerHTML={{ __html: noFlash }} />
      </head>
      <body className="bg-bg font-sans text-fg antialiased">
        <main className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6">{children}</main>
      </body>
    </html>
  );
}
`,
);

write(
  "package.json",
  JSON.stringify(
    {
      name: "whale-tracker",
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      // No Drizzle, no Neon, no pg: the tracker reads chain state only, which
      // is what lets this app build with no database configured.
      dependencies: {
        clsx: "^2.1.1",
        next: "^15.1.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        "tailwind-merge": "^2.5.5",
        zod: "^3.24.1",
      },
      devDependencies: {
        "@types/node": "^22.10.2",
        "@types/react": "^19.0.2",
        "@types/react-dom": "^19.0.2",
        autoprefixer: "^10.4.20",
        postcss: "^8.4.49",
        tailwindcss: "^3.4.17",
        typescript: "^5.7.2",
      },
      engines: { node: ">=22" },
    },
    null,
    2,
  ) + "\n",
);

write(
  "tsconfig.json",
  JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        lib: ["dom", "dom.iterable", "ES2022"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  ) + "\n",
);

write(
  "next.config.ts",
  GENERATED +
    `import type { NextConfig } from "next";

const config: NextConfig = {
  poweredByHeader: false,
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        ],
      },
    ];
  },
};

export default config;
`,
);

// Tailwind config, narrowed to this app's tree. The token mapping is the same
// one the main app uses, so the copied components render identically.
const tw = readFileSync(join(ROOT, "tailwind.config.ts"), "utf8").replace(
  /content: \[[^\]]*\]/,
  'content: ["./app/**/*.{ts,tsx}", "./features/**/*.{ts,tsx}"]',
);
write("tailwind.config.ts", tw);
copy("postcss.config.mjs");

write(
  "next-env.d.ts",
  `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n`,
);

// The RPC endpoint the tracker reads from. Not a credential — it is a public
// gateway URL — so it ships with the app and the page works on first load.
// Vercel project env vars are already in process.env when Next loads this
// file, and Next never overwrites an existing value, so anything set in the
// dashboard wins over this default without a code change.
write(
  ".env.production",
  [
    "HOLDERS_RPC_URLS=wss://robinhood.api.pocket.network",
    "HOLDERS_TOKEN=0x4d3f37a965b21ab4122e92dd41d2693e742c883b",
    "HOLDERS_PAIR=0x9b8537be00b0dc8f76f2ab8b2c6b6e79cd2a769d",
    "HOLDERS_DEXSCREENER_CHAIN=robinhood",
    "HOLDERS_GECKOTERMINAL_NETWORK=robinhood",
    "",
  ].join("\n"),
);

write(
  ".gitignore",
  ["node_modules", ".next", ".env*.local", ".vercel", "*.tsbuildinfo"].join("\n") + "\n",
);

console.log(`Generated standalone tracker app in ${OUT}`);
