/* GENERATED by scripts/build-tracker-app.ts — edit the source, not this copy. */
import type { Metadata } from "next";
import { Space_Grotesk, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const sans = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
  display: "swap",
});
const mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Whale tracker",
  description:
    "Live holder tracking from chain state: positions ranked as economic actors, with buy/sell behavior and what each stack is worth on exit.",
};

// Match the persisted theme before first paint so the page does not flash.
const noFlash = `(function(){try{var t=localStorage.getItem('tracker-theme');if(t!=='light'&&t!=='dark'){t=window.matchMedia&&window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';}document.documentElement.setAttribute('data-theme',t);}catch(e){document.documentElement.setAttribute('data-theme','dark');}})();`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="dark" className={`${sans.variable} ${mono.variable}`}>
      <head>
        <script dangerouslySetInnerHTML={{ __html: noFlash }} />
      </head>
      <body className="bg-bg font-sans text-fg antialiased">
        <main className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6">{children}</main>
      </body>
    </html>
  );
}
