/**
 * Package everything collected into one file that can be committed and read.
 *
 *   npm run sweep:bundle
 *
 * Exists because of a specific, recurring friction: the evidence lives in
 * `data/`, which is gitignored, on a machine the analysis does not run on. So
 * every time there is something to look at, the operator has to work out which
 * of six files matter, force-add past the ignore rule, and hope nothing
 * sensitive is in them. That is enough friction to stop it happening, and
 * evidence that never gets looked at is the same as evidence never collected.
 *
 * This writes a single bundle to `evidence/`, which is deliberately *not*
 * ignored, so it is one `git add` away from being shared.
 *
 * Two things it does on the way, because a bundle that is unsafe to share is
 * worse than none:
 *
 *  - **Redacts.** Anything shaped like an API key, secret or signature is
 *    replaced. None of these files should contain one — but "should" is not a
 *    guarantee, and the cost of being wrong once is an account.
 *  - **Truncates loudly.** Large logs are trimmed to the most recent rows and
 *    the bundle says exactly how many were dropped, rather than silently
 *    shipping a subset that reads as the whole.
 */

import { appendFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadEnv } from "./load-env";
import { loadTrades } from "../lib/sweep/metrics/trade-log";
import { loadTuning } from "../lib/sweep/metrics/tune-log";
import { analyse, recommendations } from "../lib/sweep/agent/learn";

loadEnv();

const arg = (name: string, fallback: string) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};

/** Rows kept per log. Enough to analyse, small enough to read in a diff. */
const MAX_ROWS = Number(arg("rows", "2000"));
const OUT_DIR = resolve(arg("dir", "evidence"));

/**
 * Anything that could be a credential, gone.
 *
 * Deliberately over-broad. A false positive costs a mangled field in a log
 * nobody was reading closely; a false negative costs the account.
 */
function redact(text: string): string {
  return text
    .replace(/(signature=)[A-Fa-f0-9]+/g, "$1<redacted>")
    .replace(/(BINANCE_API_(?:KEY|SECRET)\s*[=:]\s*)\S+/gi, "$1<redacted>")
    .replace(/\b[A-Za-z0-9]{64}\b/g, "<redacted-64>")
    .replace(/("(?:apiKey|apiSecret|secret|token|password)"\s*:\s*)"[^"]*"/gi, '$1"<redacted>"');
}

interface Part {
  name: string;
  path: string;
  rows: number;
  kept: number;
  bytes: number;
  body: string;
}

function readLog(label: string, file: string): Part | null {
  const path = resolve(file);
  if (!existsSync(path)) return null;
  const raw = readFileSync(path, "utf8");
  const lines = raw.split("\n").filter((l) => l.trim());
  const kept = lines.slice(-MAX_ROWS);
  return {
    name: label,
    path,
    rows: lines.length,
    kept: kept.length,
    bytes: statSync(path).size,
    body: redact(kept.join("\n")),
  };
}

const parts = [
  readLog("trades", process.env.SWEEP_TRADE_LOG ?? "data/sweep-trades.jsonl"),
  readLog("shadow", process.env.SWEEP_SHADOW_OUT ?? "data/sweep-shadow.jsonl"),
  readLog("paper", process.env.SWEEP_PAPER_OUT ?? "data/sweep-paper.jsonl"),
  readLog("tuning", process.env.SWEEP_TUNE_LOG ?? "data/sweep-tuning.jsonl"),
  readLog("news", process.env.SWEEP_NEWS ?? "data/sweep-news.jsonl"),
].filter((p): p is Part => p !== null);

/* ------------------------------------------------------------- the report */

const { records, skipped } = loadTrades();
const { entries } = loadTuning();
const report = analyse(records);

const limitsPath = resolve(process.env.SWEEP_LIMITS ?? "data/sweep-limits.json");
let limits: Record<string, unknown> = {};
if (existsSync(limitsPath)) {
  try {
    limits = JSON.parse(readFileSync(limitsPath, "utf8")) as Record<string, unknown>;
  } catch { /* a corrupt limits file is itself worth seeing in the bundle */ }
}

mkdirSync(OUT_DIR, { recursive: true });
const stamp = new Date().toISOString().slice(0, 16).replace(/[:T]/g, "").replace(/-/g, "");
const out = resolve(OUT_DIR, `bundle-${stamp}.md`);

const kb = (n: number) => `${(n / 1024).toFixed(1)} KB`;
const lines: string[] = [];

lines.push(`# Evidence bundle — ${new Date().toISOString()}`);
lines.push("");
lines.push("Generated by `npm run sweep:bundle`. Credentials redacted; large logs truncated to the most");
lines.push("recent rows with the count of what was dropped stated below.");
lines.push("");

lines.push("## What is here");
lines.push("");
lines.push("| Log | Rows total | Rows included | File size |");
lines.push("|---|---:|---:|---:|");
for (const p of parts) {
  lines.push(`| ${p.name} | ${p.rows} | ${p.kept}${p.kept < p.rows ? ` (dropped ${p.rows - p.kept})` : ""} | ${kb(p.bytes)} |`);
}
if (parts.length === 0) lines.push("| _nothing found_ | | | |");
lines.push("");
if (skipped > 0) lines.push(`${skipped} trade row(s) were unparseable and excluded from the analysis below.`);
lines.push("");

lines.push("## Current limits");
lines.push("");
lines.push("```json");
lines.push(JSON.stringify(limits, null, 2));
lines.push("```");
lines.push("");

lines.push("## Post-mortem");
lines.push("");
if (report.n === 0) {
  lines.push("No closed trades with recorded conditions yet.");
} else {
  for (const l of report.lines) lines.push(`- ${l}`);
  lines.push("");
  lines.push("### How the losses failed");
  lines.push("");
  if (report.anatomy.length === 0) lines.push("No losing trades recorded.");
  for (const a of report.anatomy) {
    lines.push(`**${a.kind}** — ${a.count} trades, ${(a.share * 100).toFixed(0)}% of losses, -$${a.costUsd.toFixed(2)}`);
    lines.push("");
    lines.push(a.prescription);
    for (const ex of a.examples) lines.push(`- ${ex}`);
    lines.push("");
  }
  lines.push("### Conditions");
  lines.push("");
  for (const s of report.splits.slice(0, 12)) {
    lines.push(`**${s.label}**${s.decisive ? " — worth acting on" : ""}`);
    for (const arm of s.arms) {
      lines.push(
        `- ${arm.label}: n=${arm.n}, won ${(arm.winRate * 100).toFixed(0)}% ` +
          `(${(arm.winLo * 100).toFixed(0)}-${(arm.winHi * 100).toFixed(0)}%)` +
          (arm.r.n >= 2 ? `, ${arm.r.mean >= 0 ? "+" : ""}${arm.r.mean.toFixed(2)}R` : ""),
      );
    }
    lines.push(`  ${s.note}`);
    lines.push("");
  }
  const recs = recommendations(report, {
    breakEvenAtPct: Number(limits.breakEvenAtPct ?? 60),
    stopLossPct: Number(limits.stopLossPct ?? 0.5),
    maxHoldMinutes: Number(limits.maxHoldMinutes ?? 30),
    riskPerTradePct: Number(limits.riskPerTradePct ?? 4),
  });
  lines.push("### What it suggests changing");
  lines.push("");
  if (recs.length === 0) lines.push("Nothing — the losses do not concentrate in one failure mode, or there are too few.");
  for (const r of recs) {
    lines.push(`**${r.setting}**${r.suggested !== null && r.current !== null ? ` ${r.current} → ${r.suggested}` : ""} [${r.support}]`);
    lines.push("");
    lines.push(r.why);
    lines.push("");
  }
  lines.push("### What this does not show");
  lines.push("");
  for (const c of report.caveats) lines.push(`- ${c}`);
  lines.push("");
}

lines.push("## Cap changes");
lines.push("");
if (entries.length === 0) {
  lines.push("None recorded.");
} else {
  lines.push("| When | Setting | Change | By | Why |");
  lines.push("|---|---|---|---|---|");
  for (const e of entries.slice(-40)) {
    lines.push(
      `| ${new Date(e.at).toISOString().slice(0, 16).replace("T", " ")} | ${e.setting} | ${e.from} → ${e.to} | ${e.by} | ${e.reason.replace(/\|/g, "/").slice(0, 140)} |`,
    );
  }
}
lines.push("");

lines.push("## Raw logs");
lines.push("");
lines.push("One JSON object per line, most recent last.");
lines.push("");
for (const p of parts) {
  lines.push(`### ${p.name} — \`${p.path}\``);
  lines.push("");
  lines.push("```jsonl");
  lines.push(p.body);
  lines.push("```");
  lines.push("");
}

writeFileSync(out, `${lines.join("\n")}\n`);
const size = statSync(out).size;

console.log("");
console.log(`  Bundle written to ${out}`);
console.log(`  ${kb(size)}${size > 4 * 1024 * 1024 ? "  — large; consider --rows 500" : ""}`);
console.log("");
console.log("  Share it:");
console.log(`    git add -f ${out.replace(`${process.cwd()}/`, "")}`);
console.log(`    git commit -m "evidence bundle" && git push`);
console.log("");
if (report.n > 0) {
  console.log(`  ${report.n} closed trades, ${report.anatomy.reduce((a, x) => a + x.count, 0)} losses analysed.`);
} else {
  console.log("  No closed trades yet — the bundle carries the raw logs only.");
}
console.log("");

// Keep a pointer to the newest bundle so a reader does not have to guess which
// timestamped file is current.
try {
  appendFileSync(resolve(OUT_DIR, "LATEST"), `${out}\n`);
} catch { /* the pointer is a convenience, not a requirement */ }
